



class common_keys:
    #第一次执行时间
    FIRST_TIME=6
    #第二次执行时间
    SECOND_TIME=18
    #redis数据库IP
    REDIS_IP = "10.3.1.99"
    #redis端口
    REDIS_PORT = "6379"
    REDIS_DB = "12"
    jvmPath = 'C:/File/soft/java/jre1.8/bin/server/jvm.dll'
    JAR_PATH="/home/classifier.jar"
    THULAC_MODEL_PATH = 'C:/File/soft/python36/Lib/site-packages/thulac/models'
    URL_NAME = "url"
    DATE_NAME = "date"
    TITLE_NEME = "title"
    TEXT_NEME = "text"
    RETRY_NEME = "retry"
    ERR_NAME = "err"
    TITLE_CUT = "cut"
    NAME = "name"
    RESPONSIBLE = "responsible"
    NEED = "need"

    #文件下载路径
    FILE_PATH = "C:/SpiderResultFile"
    #复制文件路径，暂时不用
    COPY_PATH = "C:/temp/file"

    #错误文件路径
    ERR_PATH = "C:/temp/err"

    #写日志的文件路径
    LOGGER_PATH = "C:/temp/loger.log"

    #rowkey路径
    # ROWKEY_PATH="/root/.kettle/kettle.properties"
    ROWKEY_PATH="C:/SpiderResultFile/kettle.properties"

    START_ROW="start_row"
    END_ROW="end_row"
    NOTE="# This file was generated by Pentaho Data Integration version 6.0.1.0-386.\n# \n# Here are a few examples of variables to set: \n#\n# PRODUCTION_SERVER = hercules\n# TEST_SERVER = zeus\n# DEVELOPMENT_SERVER = thor\n#\n# Note: lines like these with a # in front of it are comments\n#\n\n"

    CONF_NAME = "conf.cfg"


    keyword_arr1 = ["文献", "纸质", "纸本", "数据库", "画册", "杂志", "书刊", "报刊", "期刊", "刊物", "期刊订购", "原版图书", "外文图书", "纸质图书", "图书供货",
                    "图书供应", "图书购置", "图书采购", "图书资料", "图书项目", "古籍", "书籍", "电子图书", "电子资源", "全文", "馆配", "馆藏", "订购", "续订",
                    "增订", "查阅", "订阅", "阅览", "编目", "唱片", "平台采购", "数据编制", "数据处理", "数据加工", "数据获取", "数据资源", "数字资源", "网络资源",
                    "资源建设", "资料购买", "软件租赁", "爱思唯尔", "外版", "使用权", "会议录"]
    keyword_arr2 = ["图书", "书", "刊", "库", "报", "软件", "档案", "资料", "材料", "数据", "合集", "电子", "数字化", "图书馆", "索引"]
